using AhlanFeekumPro.UserProfiles;
using AhlanFeekumPro.SiteProperties;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace AhlanFeekumPro.FavoriteProperties
{
    public class FavoriteProperty : FavoritePropertyBase
    {
        //<suite-custom-code-autogenerated>
        protected FavoriteProperty()
        {

        }

        public FavoriteProperty(Guid id, Guid userProfileId, Guid sitePropertyId)
            : base(id, userProfileId, sitePropertyId)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}