using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace AhlanFeekumPro.FavoriteProperties
{
    public class FavoritePropertyManager : FavoritePropertyManagerBase
    {
        //<suite-custom-code-autogenerated>
        public FavoritePropertyManager(IFavoritePropertyRepository favoritePropertyRepository)
            : base(favoritePropertyRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}