using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using AhlanFeekumPro.Permissions;
using AhlanFeekumPro.Governorates;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using AhlanFeekumPro.Shared;

namespace AhlanFeekumPro.Governorates
{
    public class GovernoratesAppService : GovernoratesAppServiceBase, IGovernoratesAppService
    {
        //<suite-custom-code-autogenerated>
        public GovernoratesAppService(IGovernorateRepository governorateRepository, GovernorateManager governorateManager, IDistributedCache<GovernorateDownloadTokenCacheItem, string> downloadTokenCache)
            : base(governorateRepository, governorateManager, downloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}