using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using AhlanFeekumPro.Permissions;
using AhlanFeekumPro.OnlyForYouSections;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using AhlanFeekumPro.Shared;

namespace AhlanFeekumPro.OnlyForYouSections
{
    public class OnlyForYouSectionsAppService : OnlyForYouSectionsAppServiceBase, IOnlyForYouSectionsAppService
    {
        //<suite-custom-code-autogenerated>
        public OnlyForYouSectionsAppService(IOnlyForYouSectionRepository onlyForYouSectionRepository, OnlyForYouSectionManager onlyForYouSectionManager, IDistributedCache<OnlyForYouSectionDownloadTokenCacheItem, string> downloadTokenCache)
            : base(onlyForYouSectionRepository, onlyForYouSectionManager, downloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}