using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace AhlanFeekumPro.VerificationCodes
{
    public class VerificationCode : VerificationCodeBase
    {
        //<suite-custom-code-autogenerated>
        protected VerificationCode()
        {

        }

        public VerificationCode(Guid id, string phoneOrEmail, int securityCode, bool isExpired)
            : base(id, phoneOrEmail, securityCode, isExpired)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}