using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace AhlanFeekumPro.OnlyForYouSections
{
    public class OnlyForYouSection : OnlyForYouSectionBase
    {
        //<suite-custom-code-autogenerated>
        protected OnlyForYouSection()
        {

        }

        public OnlyForYouSection(Guid id, string firstPhoto, string secondPhoto, string thirdPhoto)
            : base(id, firstPhoto, secondPhoto, thirdPhoto)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}