using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace AhlanFeekumPro.OnlyForYouSections
{
    public class OnlyForYouSectionManager : OnlyForYouSectionManagerBase
    {
        //<suite-custom-code-autogenerated>
        public OnlyForYouSectionManager(IOnlyForYouSectionRepository onlyForYouSectionRepository)
            : base(onlyForYouSectionRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}