using AhlanFeekumPro.SiteProperties;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace AhlanFeekumPro.PropertyMedias
{
    public class PropertyMedia : PropertyMediaBase
    {
        //<suite-custom-code-autogenerated>
        protected PropertyMedia()
        {

        }

        public PropertyMedia(Guid id, Guid sitePropertyId, string image, int order, bool isActive)
            : base(id, sitePropertyId, image, order, isActive)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}