using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace AhlanFeekumPro.PropertyMedias
{
    public class PropertyMediaManager : PropertyMediaManagerBase
    {
        //<suite-custom-code-autogenerated>
        public PropertyMediaManager(IPropertyMediaRepository propertyMediaRepository)
            : base(propertyMediaRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}