using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace AhlanFeekumPro.PropertyEvaluations
{
    public class PropertyEvaluationManager : PropertyEvaluationManagerBase
    {
        //<suite-custom-code-autogenerated>
        public PropertyEvaluationManager(IPropertyEvaluationRepository propertyEvaluationRepository)
            : base(propertyEvaluationRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}