using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace AhlanFeekumPro.PersonEvaluations
{
    public class PersonEvaluationManager : PersonEvaluationManagerBase
    {
        //<suite-custom-code-autogenerated>
        public PersonEvaluationManager(IPersonEvaluationRepository personEvaluationRepository)
            : base(personEvaluationRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}