using AhlanFeekumPro.UserProfiles;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace AhlanFeekumPro.PersonEvaluations
{
    public class PersonEvaluation : PersonEvaluationBase
    {
        //<suite-custom-code-autogenerated>
        protected PersonEvaluation()
        {

        }

        public PersonEvaluation(Guid id, Guid evaluatorId, Guid evaluatedPersonId, int rate, string? comment = null)
            : base(id, evaluatorId, evaluatedPersonId, rate, comment)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}