using AhlanFeekumPro.Governorates;
using AhlanFeekumPro.PropertyTypes;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace AhlanFeekumPro.SiteProperties
{
    public class SiteProperty : SitePropertyBase
    {
        //<suite-custom-code-autogenerated>
        protected SiteProperty()
        {

        }

        public SiteProperty(Guid id, Guid propertyTypeId, Guid governorateId, string propertyTitle, int bedrooms, int bathrooms, int numberOfBed, int floor, int maximumNumberOfGuest, int livingrooms, string propertyDescription, int pricePerNight, bool isActive, string? hotelName = null, string? hourseRules = null, string? importantInformation = null, string? address = null, string? streetAndBuildingNumber = null, string? landMark = null)
            : base(id, propertyTypeId, governorateId, propertyTitle, bedrooms, bathrooms, numberOfBed, floor, maximumNumberOfGuest, livingrooms, propertyDescription, pricePerNight, isActive, hotelName, hourseRules, importantInformation, address, streetAndBuildingNumber, landMark)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}