using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace AhlanFeekumPro.Governorates
{
    public class GovernorateManager : GovernorateManagerBase
    {
        //<suite-custom-code-autogenerated>
        public GovernorateManager(IGovernorateRepository governorateRepository)
            : base(governorateRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}