using AhlanFeekumPro.Shared;
using AhlanFeekumPro.SiteProperties;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using AhlanFeekumPro.Permissions;
using AhlanFeekumPro.PropertyCalendars;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using AhlanFeekumPro.Shared;

namespace AhlanFeekumPro.PropertyCalendars
{
    public class PropertyCalendarsAppService : PropertyCalendarsAppServiceBase, IPropertyCalendarsAppService
    {
        //<suite-custom-code-autogenerated>
        public PropertyCalendarsAppService(IPropertyCalendarRepository propertyCalendarRepository, PropertyCalendarManager propertyCalendarManager, IDistributedCache<PropertyCalendarDownloadTokenCacheItem, string> downloadTokenCache, IRepository<AhlanFeekumPro.SiteProperties.SiteProperty, Guid> sitePropertyRepository)
            : base(propertyCalendarRepository, propertyCalendarManager, downloadTokenCache, sitePropertyRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}