using AhlanFeekumPro.Shared;
using AhlanFeekumPro.PropertyFeatures;
using AhlanFeekumPro.PropertyTypes;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using AhlanFeekumPro.Permissions;
using AhlanFeekumPro.SiteProperties;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using AhlanFeekumPro.Shared;

namespace AhlanFeekumPro.SiteProperties
{
    public class SitePropertiesAppService : SitePropertiesAppServiceBase, ISitePropertiesAppService
    {
        //<suite-custom-code-autogenerated>
        public SitePropertiesAppService(ISitePropertyRepository sitePropertyRepository, SitePropertyManager sitePropertyManager, IDistributedCache<SitePropertyDownloadTokenCacheItem, string> downloadTokenCache, IRepository<AhlanFeekumPro.PropertyTypes.PropertyType, Guid> propertyTypeRepository, IRepository<AhlanFeekumPro.PropertyFeatures.PropertyFeature, Guid> propertyFeatureRepository)
            : base(sitePropertyRepository, sitePropertyManager, downloadTokenCache, propertyTypeRepository, propertyFeatureRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}