using AhlanFeekumPro.MobileResponses;
using AhlanFeekumPro.Permissions;
using AhlanFeekumPro.Shared;
using AhlanFeekumPro.Shared;
using AhlanFeekumPro.UserProfiles;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Caching.Distributed;
using MiniExcelLibs;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Linq.Dynamic.Core;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Volo.Abp.Content;
using Volo.Abp.Domain.Repositories;
using Volo.Abp.Identity;

namespace AhlanFeekumPro.UserProfiles
{
    public class UserProfilesAppService : UserProfilesAppServiceBase, IUserProfilesAppService
    {
        //<suite-custom-code-autogenerated>
        public UserProfilesAppService(IUserProfileRepository userProfileRepository, UserProfileManager userProfileManager, IDistributedCache<UserProfileDownloadTokenCacheItem, string> downloadTokenCache, IRepository<Volo.Abp.Identity.IdentityRole, Guid> identityRoleRepository, IRepository<Volo.Abp.Identity.IdentityUser, Guid> identityUserRepository)
            : base(userProfileRepository, userProfileManager, downloadTokenCache, identityRoleRepository, identityUserRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
        [AllowAnonymous]
        public virtual async Task<MobileResponseDto> RegisterAsync(RegisterCreateDto input)
        {
            var user = await _userProfileManager.CreatWithDetialsAsync(input.Name, input.IsSuperHost, input.Password, input.ProfilePhoto, input.RoleId, input.Email, input.PhoneNumber, input.Latitude, input.Longitude, input.Address);
            return ObjectMapper.Map<MobileResponse, MobileResponseDto>(user);
        }
    }
}