using Volo.Abp.Identity;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace AhlanFeekumPro.UserProfiles
{
    public class UserProfile : UserProfileBase
    {
        //<suite-custom-code-autogenerated>
        protected UserProfile()
        {

        }

        public UserProfile(Guid id, Guid? identityRoleId, Guid identityUserId, string name, bool isSuperHost, string? email = null, string? phoneNumber = null, string? latitude = null, string? longitude = null, string? address = null, string? profilePhoto = null)
            : base(id, identityRoleId, identityUserId, name, isSuperHost, email, phoneNumber, latitude, longitude, address, profilePhoto)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}