using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace AhlanFeekumPro.PropertyTypes
{
    public class PropertyTypeManager : PropertyTypeManagerBase
    {
        //<suite-custom-code-autogenerated>
        public PropertyTypeManager(IPropertyTypeRepository propertyTypeRepository)
            : base(propertyTypeRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}