using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace AhlanFeekumPro.PropertyFeatures
{
    public class PropertyFeatureManager : PropertyFeatureManagerBase
    {
        //<suite-custom-code-autogenerated>
        public PropertyFeatureManager(IPropertyFeatureRepository propertyFeatureRepository)
            : base(propertyFeatureRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}