using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace AhlanFeekumPro.PropertyFeatures
{
    public class PropertyFeature : PropertyFeatureBase
    {
        //<suite-custom-code-autogenerated>
        protected PropertyFeature()
        {

        }

        public PropertyFeature(Guid id, string title, string icon, int order, bool isActive)
            : base(id, title, icon, order, isActive)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}