using AhlanFeekumPro.SiteProperties;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace AhlanFeekumPro.PropertyCalendars
{
    public class PropertyCalendar : PropertyCalendarBase
    {
        //<suite-custom-code-autogenerated>
        protected PropertyCalendar()
        {

        }

        public PropertyCalendar(Guid id, Guid sitePropertyId, DateOnly date, bool isAvailable, float? price = null, string? note = null)
            : base(id, sitePropertyId, date, isAvailable, price, note)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}