using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace AhlanFeekumPro.PropertyCalendars
{
    public class PropertyCalendarManager : PropertyCalendarManagerBase
    {
        //<suite-custom-code-autogenerated>
        public PropertyCalendarManager(IPropertyCalendarRepository propertyCalendarRepository)
            : base(propertyCalendarRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}