using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using AhlanFeekumPro.Permissions;
using AhlanFeekumPro.PropertyFeatures;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using AhlanFeekumPro.Shared;

namespace AhlanFeekumPro.PropertyFeatures
{
    public class PropertyFeaturesAppService : PropertyFeaturesAppServiceBase, IPropertyFeaturesAppService
    {
        //<suite-custom-code-autogenerated>
        public PropertyFeaturesAppService(IPropertyFeatureRepository propertyFeatureRepository, PropertyFeatureManager propertyFeatureManager, IDistributedCache<PropertyFeatureDownloadTokenCacheItem, string> downloadTokenCache)
            : base(propertyFeatureRepository, propertyFeatureManager, downloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}