using AhlanFeekumPro.UserProfiles;
using AhlanFeekumPro.SiteProperties;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace AhlanFeekumPro.SpecialAdvertisments
{
    public class SpecialAdvertisment : SpecialAdvertismentBase
    {
        //<suite-custom-code-autogenerated>
        protected SpecialAdvertisment()
        {

        }

        public SpecialAdvertisment(Guid id, Guid sitePropertyId, Guid imageId, int order, bool isActive)
            : base(id, sitePropertyId, imageId, order, isActive)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}