using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace AhlanFeekumPro.SpecialAdvertisments
{
    public class SpecialAdvertismentManager : SpecialAdvertismentManagerBase
    {
        //<suite-custom-code-autogenerated>
        public SpecialAdvertismentManager(ISpecialAdvertismentRepository specialAdvertismentRepository)
            : base(specialAdvertismentRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}